USE DRFINGERPRINTS;

#Removes 3 columns from songs table.
ALTER TABLE songs
DROP COLUMN audio_format,
DROP COLUMN song_name,
DROP COLUMN artist;

#Drops stored procedures
DROP PROCEDURE IF EXISTS FINGERID_D;
DROP PROCEDURE IF EXISTS FINGERID_IU;
DROP PROCEDURE IF EXISTS SUBFINGERID_D;
DROP PROCEDURE IF EXISTS SUBFINGERID_IU;

#Creates the necessary stored procedures again:
DELIMITER $$

DROP PROCEDURE IF EXISTS SUBFINGERID_D$$

CREATE PROCEDURE SUBFINGERID_D (
    IN parREFERENCE     VARCHAR(20)
)
exit_proc:BEGIN
-- YN 2015-08-18
  DECLARE _TRACK_ID    INT;

  SET _TRACK_ID = NULL;

  
  SELECT ID
           INTO _TRACK_ID
  FROM   SONGS
  WHERE  REFERENCE = parREFERENCE;

  IF _TRACK_ID IS NOT NULL THEN
    DELETE FROM SUBFINGERID WHERE ID = _TRACK_ID;
END IF;

END$$

DELIMITER ;


DELIMITER $$

DROP PROCEDURE IF EXISTS SUBFINGERID_IU$$

CREATE PROCEDURE SUBFINGERID_IU (
    IN parREFERENCE     	VARCHAR(20),
	IN parDR_DISKOTEKSNR 	INT,
    IN parSIDENUMMER		INT,
    IN parSEKVENSNUMMER		INT,
    IN parDURATION		    BIGINT,
    IN parSIGNATURE         LONGBLOB
)
exit_proc:BEGIN
-- YN 2015-08-21
-- 
  DECLARE _TRACK_ID    INT;

  SET _TRACK_ID = NULL;
  
  SELECT ID
           INTO _TRACK_ID
  FROM   SONGS
  WHERE  REFERENCE = parREFERENCE;

  IF _TRACK_ID IS NULL THEN

    INSERT INTO SONGS (    
               REFERENCE,
               DR_DISKOTEKSNR,
               SIDENUMMER,
               SEKVENSNUMMER,
               DURATION
               )
    VALUES(	parREFERENCE,
			parDR_DISKOTEKSNR,
            parSIDENUMMER,
            parSEKVENSNUMMER,
			parDURATION);
    
    SET _TRACK_ID = LAST_INSERT_ID();

  ELSE

    UPDATE SONGS
      SET 
			DR_DISKOTEKSNR = IFNULL(parDR_DISKOTEKSNR, DR_DISKOTEKSNR),
			SIDENUMMER = IFNULL(parSIDENUMMER, SIDENUMMER),
			SEKVENSNUMMER = IFNULL(parSEKVENSNUMMER, SEKVENSNUMMER),
			DURATION = IFNULL(parDURATION, DURATION)
    WHERE ID = _TRACK_ID;

  END IF;

  DELETE FROM SUBFINGERID
  WHERE ID = _TRACK_ID;

  INSERT INTO SUBFINGERID (    
              ID,
              SIGNATURE)
  VALUES(_TRACK_ID,
         parSIGNATURE); 
  SELECT _TRACK_ID AS ID;

END$$

DELIMITER ;



