USE DRFINGERPRINTS;

--Stored procedures for checking if song already is fingerprinted
DROP PROCEDURE IF EXISTS CHECK_IF_SONG_FP;

DELIMITER //
CREATE PROCEDURE CHECK_IF_SONG_FP(
    IN parDR_DISKOTEKSNR INT,
    IN parSIDENUMMER INT,
    IN parSEKVENSNUMMER INT
)
 
BEGIN
	SELECT COUNT(*)
	FROM SONGS S
	WHERE
		parDR_DISKOTEKSNR = S.DR_DISKOTEKSNR AND
		parSIDENUMMER = S.SIDENUMMER AND
		parSEKVENSNUMMER = S.SEKVENSNUMMER;
   END //
DELIMITER ;
