use DRFINGERPRINTS;

#Deletes the results within an interval.
DROP PROCEDURE IF EXISTS REMOVE_INTERVAL;

DELIMITER //
CREATE PROCEDURE REMOVE_INTERVAL(
	IN parCHANNEL_ID VARCHAR(19),
	IN parSTART TIMESTAMP,
	IN parEND TIMESTAMP
)
BEGIN 
	DELETE FROM LIVESTREAM_RESULTS 
	WHERE CHANNEL_ID like parCHANNEL_ID 
    AND (PLAY_DATE BETWEEN parSTART AND parEND);
END //
DELIMITER ;

